import { Voxturr, Growth, Samplrr, VoxturrLabs } from "@/src/utils/Image";
import { ReactElement } from "react";

export const HeaderData = [
  {
    id: 1,
    title: "Verticals",
    link: "",
    page: [
      {
        id: 101,
        title: "Voxturr",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <Voxturr/>,
        fillIcon: <Voxturr/>,
        subPage: [
          {
            id: 1001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet consectetur. Amet convallis sit auctor viverra.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet consectetur. Amet convallis sit auctor viverra.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon:<Growth/>,
          },
          {
            id: 1004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
      {
        id: 102,
        title: "Voxturrlabs",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <VoxturrLabs/>,
        fillIcon: <VoxturrLabs/>,
        subPage: [
          {
            id: 1001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
      {
        id: 103,
        title: "Samplrr",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <Samplrr/>,
        fillIcon: <Samplrr/>,
        subPage: [
          {
            id: 1001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 1008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
    ],
    subPage: [],
  },
  {
    id: 2,
    title: "Industries",
    link: "",
    page: [
      {
        id: 201,
        title: "Voxturr",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <Voxturr/>,
        fillIcon: <Voxturr/>,
        subPage: [
          {
            id: 2001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
      {
        id: 202,
        title: "Voxturrlabs",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <VoxturrLabs/>,
        fillIcon: <VoxturrLabs/>,
        subPage: [
          {
            id: 2001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
      {
        id: 203,
        title: "Samplrr",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <Samplrr/>,
        fillIcon: <Samplrr/>,
        subPage: [
          {
            id: 2001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 2006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
    ],
    subPage: [],
  },
  {
    id: 3,
    title: "Insight",
    link: "",
    page: [
      {
        id: 301,
        title: "Voxturr",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <Voxturr/>,
        fillIcon: <Voxturr/>,
        subPage: [
          {
            id: 3001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3006,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3007,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3008,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
      {
        id: 302,
        title: "Voxturrlabs",
        description: "Lorem ipsum dolor sit amet Mattis.",
        link: "",
        icon: <VoxturrLabs/>,
        fillIcon: <VoxturrLabs/>,
        subPage: [
          {
            id: 3001,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3002,
            title: "Audience Segmentation",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3003,
            title: "SaaS Marketing",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3004,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
          {
            id: 3005,
            title: "Growth Hacking",
            description: "Lorem ipsum dolor sit amet Mattis.",
            link: "",
            icon: <Growth/>,
            fillIcon: <Growth/>,
          },
        ],
      },
    ],
    subPage: [],
  },
  {
    id: 4,
    title: "Work",
    link: "/work",
    page: [],
    subPage: [],
  },
  {
    id: 5,
    title: "About Us",
    link: "/about-us",
    page: [],
    subPage: [],
  },
];
